### ISSUE TITLE
Problem Loading

### ISSUE THREAD

**Issue by Grifter1** [0xFireball/MK.MobileDevice#13]
Starting the imobiledevice-net demo

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libimobile
device': The specified module could not be found. (Exception from HRESULT: 0x800
7007E)
   at iMobileDevice.iDevice.iDeviceNativeMethods.idevice_get_device_list(ReadOnl
yCollection`1& devices, Int32& count)
   at iMobileDevice.iDevice.iDeviceApi.idevice_get_device_list(ReadOnlyCollectio
n`1& devices, Int32& count)
   at ConsoleApplication3.Program.Main(String[] args) in c:\Users\Egzon\Document
s\Visual Studio 2013\Projects\ConsoleApplication3\ConsoleApplication3\Program.cs
:line 29

How to fix it ?

**Comment by 0xFireball** [comment]
The `libimobiledevice.dll` library was not found. You need to include the Driver DLLs for MK.MobileDevice in the binary directory of your application:

When building examples, you will need to copy the files from the DriverDLLs/ folder to your project's output directory regardless of whether you are 32-bit or 64-bit, as the project is being compiled for x86 and not x64. In your own projects, you can use either; however, your C# project must be being built for the x64 platform for the 64-bit drivers to work.

This should solve your problem. Let me know if you still have any issues.
