### ISSUE TITLE
Can't detect iPhone. 

### ISSUE THREAD

**Issue by phantom1988** [0xFireball/MK.MobileDevice#14]
I have written a code using MK.MobileDevice to identify various information about iPhones. But I can't seems to get the application to detect the iPhone when plugged in to the computer. 

Please find the below code with the project and  I appreciate if you could let me know what needs to be done to get the phones detected (running on different versions of iOS including iOS 10) 

https://1drv.ms/u/s!Ap2MvQdfFd8otEu6jpN5PH4qQnf0

Thank you.

**Comment by 0xFireball** [comment]
@phantom1988 Please see #11 
iOS 10 switched to a newer GNUTLS version. I'll need to recompile the native libraries and make the modifications, then everything should work again.

As of now, every non-iOS 10 device should work perfectly.
