### ISSUE TITLE
Do you plan to add a device activation function?

### ISSUE THREAD

**Issue by jackczhang** [0xFireball/MK.MobileDevice#4]
Do you plan to add active funtion on the iphone?

**Comment by 0xFireball** [comment]
Hello, @jackczhang 
Can you please be more specific? I'm not sure I understand your question

**Comment by 0xFireball** [comment]
@jackczhang , can you clarify? this issue has been inactive and I will close it if you do not respond. Thanks.

**Comment by jackczhang** [comment]
Sorry for my pool English, I mean if you can add iphone activation funtion, I only found the deactivate function.

**Comment by 0xFireball** [comment]
Oh activation. I didn't add that earlier, but I can do it when time permits. If you have time, you can do it too. Here's the documentation:

http://www.libimobiledevice.org/docs/html/lockdown_8h.html#ab6e9e8e04da0e8022d31b08b77232fb7

Please also take a look at this for contributing. Feel free to implement and pull request.

Here's info for contributing: https://github.com/exaphaser/MK.MobileDevice/wiki/Contributing
I will add it when I have some time. Possibly in a few days, if that's all right.

**Comment by 0xFireball** [comment]
@jackczhang just curious, why do you want this feature? It's not that hard to activate manually. Also, this library is GPL, so please make sure you are in compliance with the license. If you are using this project in your program, you must disclose the source. Here's more info on the license:
https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

**Comment by 0xFireball** [comment]
I will work on this soon, probably in the next week.
