### ISSUE TITLE
[Question] iPhone.GetIconLayout and SetIconLayout 

### ISSUE THREAD

**Issue by AjayGhale** [0xFireball/MK.MobileDevice#7]
Hi, im having some problems trying to get the icons layout and display it on my app. 

may i know how to exactly use this method? 
thanks in advance

**Comment by 0xFireball** [comment]
See #3 . More information later if you need it.

**Comment by 0xFireball** [comment]
Why don't you try and see if you can get something working in the meantime?

**Comment by 0xFireball** [comment]
If you are having problems, can you give me specifics? Post your code here and I may be able to help you.

**Comment by AjayGhale** [comment]
hi men, give me an email address so we can talk in private
