### ISSUE TITLE
[help] i need help to use IconLayout and GetApplicationList

### ISSUE THREAD

**Issue by AjayGhale** [0xFireball/MK.MobileDevice#9]
could you guys help me? i managed to display the installed apps of the device on a ListBox using

`iph.GetApplicationList();
        {
            string[] appNames = iph.GetApplicationList().Select(app=>app.Name).ToArray();

            string[] appVersion = iph.GetApplicationList().Select(app => app.Version).ToArray();

            this.listBox1.Items.AddRange(appNames);
        }`

but the apps are displayed like simple text, i just want to display the apps like on iTools for example, the app icon and below the app name is there any way one of you guys help me to do that?

and also how can i display the icons layout?
THANKS IN ADVANCE

**Comment by AjayGhale** [comment]
why i get always closed the issues and no help ??

**Comment by 0xFireball** [comment]
Sorry about any misunderstanding. I will help you, I am just very busy right now. I closed the issue because it is a question.
Please allow me about a week.

**Comment by AjayGhale** [comment]
uh... sorry man really sorry whenyou have a  chance shoot me an email at avilacef@gmail.com thanks and again sorry!! have a nice day

**Comment by 0xFireball** [comment]
Hello AjayGhale,

Hello,

The Application class will give you a lot of metadata about installed apps.
As for layout, there should be methods available to get and set icon layout as an XDocument.

You will basically get an XML document that contains the home screen layout of the device.
Let me know if you need any more help.
